version: "3"

networks:
  proxy:
    driver: bridge
  router_eliotctl:
    internal: true
  router_wellcheck:
    internal: true
  router_newtechstack:
    internal: true
  internal_eliotctl:
    internal: true
  internal_wellcheck:
    internal: true
  internal_newtechstack:
    internal: true

services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Proxy/logs/global:/var/log/nginx
      - ./Proxy/conf/:/etc/nginx/conf.d/
      - ./Proxy/vhost:/etc/nginx/vhost.d
      - ./Proxy/data/html:/usr/share/nginx/html
      - ./Proxy/data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - ./Proxy/vhost:/etc/nginx/vhost.d
      - ./Proxy/data/html:/usr/share/nginx/html
      - ./Proxy/data/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
    networks:
      - proxy

  router:
    image: nginx
    container_name: router
    restart: always
    volumes:
      - ./Router/conf/router.conf:/etc/nginx/nginx.conf:ro
    links:
      - eliotctl_landing
      - wellcheck_landing
      - newtechstack_landing
    networks:
      - proxy
      - router_eliotctl
      - router_wellcheck
      - router_newtechstack
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}

  eliotctl_landing:
    image: nginx
    container_name: eliotctl_landing
    restart: always
    volumes:
      - ./Eliotctl/landing/front:/usr/share/nginx/html:ro
      - ./Eliotctl/landing/conf/landing.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - eliotctl_error
      - eliotctl_php
    networks:
      - router_eliotctl
      - internal_eliotctl

  eliotctl_php:
    build:
      context: ./Eliotctl/php
      dockerfile: Dockerfile
    container_name: eliotctl_php
    restart: always
    hostname: ${DOMAIN}
    volumes:
      - ./Eliotctl/landing/front:/usr/share/nginx/html:ro
      - ./Eliotctl/landing/contact/contact.txt:/contact.txt:rw
    networks:
      - internal_eliotctl
    environment:
      CONTACTEMAIL: ${CONTACTEMAIL}

  eliotctl_error:
    image: nginx
    container_name: eliotctl_error
    restart: always
    volumes:
      - ./Eliotctl/error/front:/usr/share/nginx/html:ro
      - ./Eliotctl/error/conf/error.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal_eliotctl

  wellcheck_landing:
    image: nginx
    container_name: wellcheck_landing
    restart: always
    volumes:
      - ./Wellcheck/landing/front:/usr/share/nginx/html:ro
      - ./Wellcheck/landing/conf/landing.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - wellcheck_error
    networks:
      - router_wellcheck
      - internal_wellcheck

  wellcheck_error:
    image: nginx
    container_name: wellcheck_error
    restart: always
    volumes:
      - ./Wellcheck/error/front:/usr/share/nginx/html:ro
      - ./Wellcheck/error/conf/error.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal_wellcheck

  newtechstack_landing:
    image: nginx
    container_name: newtechstack_landing
    restart: always
    volumes:
      - ./Newtechstack/front/web/front:/usr/share/nginx/html:ro
      - ./Newtechstack/front/web/conf/landing.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - newtechstack_error
    networks:
      - router_newtechstack
      - internal_newtechstack

  newtechstack_error:
    image: nginx
    container_name: newtechstack_error
    restart: always
    volumes:
      - ./Newtechstack/front/error/front:/usr/share/nginx/html:ro
      - ./Newtechstack/front/error/conf/error.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal_newtechstack
