version: '3'
networks:
   proxy:
     external:
       name: docker-compose_proxy

services:
   eliotctl_landing:
      image: nginx
      container_name: eliotctl_landing
      restart: always
      volumes:
        - ../Eliotctl/landing/frontend:/usr/share/nginx/html:ro
        - ../Eliotctl/landing/conf/landing.conf:/etc/nginx/conf.d/default.conf:ro
      links:
        - eliotctl_error
        - eliotctl_php
      networks:
        - proxy
      environment:
        VIRTUAL_HOST: ${DOMAIN}, www.${DOMAIN}
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: ${DOMAIN}, www.${DOMAIN}
        LETSENCRYPT_EMAIL: ${EMAIL}

   eliotctl_php:
      build:
        context: ../php
        dockerfile: Dockerfile
      container_name: eliotctl_php
      volumes:
        - ../Eliotctl/landing/frontend:/usr/share/nginx/html:ro
        - ../Eliotctl/admin/services/contact:/result
      networks:
        - proxy

   eliotctl_error:
      image: nginx
      container_name: eliotctl_error
      restart: always
      volumes:
        - ../Eliotctl/error/front:/usr/share/nginx/html:ro
        - ../Eliotctl/error/conf/error.conf:/etc/nginx/conf.d/default.conf:ro
      networks:
        - proxy
